- name: Digital Strategy
  color_icon: /assets/images/strategy-red.svg
  white_icon: /assets/images/strategy-white.svg
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit ipsam quo magni ab, veniam at adipisci obcaecati, iusto natus eaque maxime! Aliquam animi iusto placeat possimus facilis quam expedita et.
  class: strategy
- name: WeChat Mini Programs
  color_icon: /assets/images/wechat-green.svg
  white_icon: /assets/images/wechat-white.svg
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit ipsam quo magni ab, veniam at adipisci obcaecati, iusto natus eaque maxime! Aliquam animi iusto placeat possimus facilis quam expedita et.
  class: wechat
- name: Websites
  color_icon: /assets/images/website-blue.svg
  white_icon: /assets/images/website-white.svg
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit ipsam quo magni ab, veniam at adipisci obcaecati, iusto natus eaque maxime! Aliquam animi iusto placeat possimus facilis quam expedita et.
  class: website
- name: Web Apps
  color_icon: /assets/images/webapp-blue.svg
  white_icon: /assets/images/webapp-white.svg
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit ipsam quo magni ab, veniam at adipisci obcaecati, iusto natus eaque maxime! Aliquam animi iusto placeat possimus facilis quam expedita et.
  class: webapp
- name: Workshops
  color_icon: /assets/images/workshop-blue.svg
  white_icon: /assets/images/workshop-white.svg
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit ipsam quo magni ab, veniam at adipisci obcaecati, iusto natus eaque maxime! Aliquam animi iusto placeat possimus facilis quam expedita et.
  class: workshop